version: "3"

services:
  server:
    container_name: "eks-test-server"
    image: khiroki86/eks-test:golang-v1
    expose:
      - "9000"
    ports:
      - "9000:9000"
    tty: true

  proxy:
    container_name: "eks-test-envoy"
    image: khiroki86/eks-test:envoy-v1
    expose:
      - "8080"
    ports:
      - "8080:8080"
    links:
      - "server"
    tty: true
