apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  type: NodePort
  selector:
    app: envoy-lb
  ports:
    - name: proxy
      protocol: TCP
      nodePort: 30000
      port: 80
      targetPort: 80
    - name: admin
      protocol: TCP
      nodePort: 30001
      port: 9901
      targetPort: 9901
