settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: server
    path: ./src
    commands:
      run:
        status: true
    watcher:
      extensions:
        - go
        - yaml
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
